export const ENV = {
  appId: process.env.APP_ID ?? "cropwise",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  aiApiUrl: process.env.AI_API_URL ?? "https://api.openai.com",
  aiApiKey: process.env.AI_API_KEY ?? "",
  aiModel: process.env.AI_MODEL ?? "gpt-4o-mini",
  imageModel: process.env.AI_IMAGE_MODEL ?? "gpt-image-1",
  googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? "",
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID ?? "",
  awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY ?? "",
  awsRegion: process.env.AWS_REGION ?? "",
  awsBucket: process.env.AWS_S3_BUCKET ?? "",
  storageMode: process.env.STORAGE_MODE ?? "local",
  localStorageDir: process.env.LOCAL_STORAGE_DIR ?? "uploads",
};
